# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.3.0"
selene = "Kampfkarren/selene@0.26.1"
wally = "UpliftGames/wally@0.3.2"
luau-lsp = "JohnnyMorganz/luau-lsp@1.27.0"
stylua = "JohnnyMorganz/StyLua@0.20.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.2.1"
rbxcloud = "Sleitnick/rbxcloud@0.5.0"
lune = "filiptibell/lune@0.7.11"
